name: chores

on:
  push:
    branches:
      - master

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: alstr/todo-to-issue-action@v4.0.6
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
